// <auto-generated />
using System;
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations
{
    [DbContext(typeof(TollDbContext))]
    partial class TollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Bases.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);

                    b.HasDiscriminator<string>("VehicleType").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Tolls.DailyTollSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ForDay")
                        .HasColumnType("date");

                    b.Property<Guid?>("TollInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TollInvoiceId");

                    b.HasIndex("VehicleId", "ForDay")
                        .IsUnique();

                    b.ToTable("DailyTollSummaries", (string)null);
                });

            modelBuilder.Entity("Entities.Tolls.TollEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DailyTollSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DailyTollSummaryId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TollEvents", (string)null);
                });

            modelBuilder.Entity("Entities.Tolls.TollInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FromDay")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ToDay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("TollInvoices", (string)null);
                });

            modelBuilder.Entity("Entities.Vehicels.Car", b =>
                {
                    b.HasBaseType("Entities.Bases.Vehicle");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("Entities.Vehicels.Diplomat", b =>
                {
                    b.HasBaseType("Entities.Bases.Vehicle");

                    b.HasDiscriminator().HasValue("Diplomat");
                });

            modelBuilder.Entity("Entities.Vehicels.Emergency", b =>
                {
                    b.HasBaseType("Entities.Bases.Vehicle");

                    b.HasDiscriminator().HasValue("Emergency");
                });

            modelBuilder.Entity("Entities.Vehicels.Foreign", b =>
                {
                    b.HasBaseType("Entities.Bases.Vehicle");

                    b.HasDiscriminator().HasValue("Foreign");
                });

            modelBuilder.Entity("Entities.Vehicels.Military", b =>
                {
                    b.HasBaseType("Entities.Bases.Vehicle");

                    b.HasDiscriminator().HasValue("Military");
                });

            modelBuilder.Entity("Entities.Vehicels.Motorbike", b =>
                {
                    b.HasBaseType("Entities.Bases.Vehicle");

                    b.HasDiscriminator().HasValue("Motorbike");
                });

            modelBuilder.Entity("Entities.Vehicels.Tractor", b =>
                {
                    b.HasBaseType("Entities.Bases.Vehicle");

                    b.HasDiscriminator().HasValue("Tractor");
                });

            modelBuilder.Entity("Entities.Tolls.DailyTollSummary", b =>
                {
                    b.HasOne("Entities.Tolls.TollInvoice", "TollInvoice")
                        .WithMany("TollSummary")
                        .HasForeignKey("TollInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Bases.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TollInvoice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Entities.Tolls.TollEvent", b =>
                {
                    b.HasOne("Entities.Tolls.DailyTollSummary", "DailyTollSummaries")
                        .WithMany("TollEvents")
                        .HasForeignKey("DailyTollSummaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Bases.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyTollSummaries");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Entities.Tolls.DailyTollSummary", b =>
                {
                    b.Navigation("TollEvents");
                });

            modelBuilder.Entity("Entities.Tolls.TollInvoice", b =>
                {
                    b.Navigation("TollSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
